# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  # Toggle cells between 'X', 'O', 'X?', 'O?', and ''
  symbols = [
    'X'
    'O'
    'X?'
    'O?'
    ''
  ]
  $('td.cell').click ->
    current = $(this).text()
    i = 0
    while i < symbols.length
      if current == symbols[i]
        $(this).html symbols[i % symbols.length] #*** Why not -1?
        break
      i++
    return
  return

# ---
# generated by js2coffee 2.1.0